# Generated by Django 4.2.11 on 2026-05-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total (VES)')),
                ('nro_control', models.CharField(max_length=50, verbose_name='Nro. Control Fiscal')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.membership', verbose_name='Membresía')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
