# Generated by Django 4.2.11 on 2026-05-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_ves', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa VES/$')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='precio',
        ),
        migrations.AddField(
            model_name='invoice',
            name='esta_impresa',
            field=models.BooleanField(default=False, verbose_name='¿Está Impresa?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio (USD)'),
            preserve_default=False,
        ),
    ]
