# Generated by Django 4.2.11 on 2026-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_hora_fin_plan_hora_inicio_plan_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='tasa_ves',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tasa VES/$'),
        ),
    ]
