# Generated by Django 4.2.11 on 2026-05-21 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_foto'),
        ('billing', '0005_alter_exchangerate_tasa_ves'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client', verbose_name='Afiliado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='plan_snapshot',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plan Comprado'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.membership', verbose_name='Membresía'),
        ),
    ]
