# Generated by Django 4.2.11 on 2026-06-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_service_period_queued_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientserviceperiod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
