from django.urls import path
from .views import (
    ChargeCheckoutView,
    SaleItemListView,
    SaleItemCreateView,
    SaleItemUpdateView,
    SaleItemDeleteView,
    RenewPlanView,
    ChangeCutDateView,
    PaymentPeriodPreviewView,
    PaymentSuccessView,
    PlanListView,
    PlanCreateView,
    PlanUpdateView,
    PlanDeleteView,
    MembershipDeleteView,
    ExchangeRateUpdateView,
    InvoiceListView,
    InvoiceDetailView,
    PrintInvoiceActionView,
    InvoiceDeleteView,
    ReportView,
    ReportSendView,
)

app_name = 'billing'

urlpatterns = [
    path('cobro/<str:codigo_afiliado>/', ChargeCheckoutView.as_view(), name='charge_checkout'),
    path('renovar/<str:codigo_afiliado>/', RenewPlanView.as_view(), name='renew_plan'),
    path('preview-cobro/<str:codigo_afiliado>/', PaymentPeriodPreviewView.as_view(), name='payment_preview'),
    path('cobro-exito/<int:pk>/', PaymentSuccessView.as_view(), name='payment_success'),
    path('corte/<str:codigo_afiliado>/', ChangeCutDateView.as_view(), name='change_cut_date'),
    path('productos/', SaleItemListView.as_view(), name='product_list'),
    path('productos/nuevo/', SaleItemCreateView.as_view(), name='product_create'),
    path('productos/<int:pk>/editar/', SaleItemUpdateView.as_view(), name='product_update'),
    path('productos/<int:pk>/eliminar/', SaleItemDeleteView.as_view(), name='product_delete'),
    path('planes/', PlanListView.as_view(), name='plan_list'),
    path('planes/nuevo/', PlanCreateView.as_view(), name='plan_create'),
    path('planes/editar/<int:pk>/', PlanUpdateView.as_view(), name='plan_update'),
    path('planes/borrar/<int:pk>/', PlanDeleteView.as_view(), name='plan_delete'),
    path('membresia/eliminar/<int:pk>/', MembershipDeleteView.as_view(), name='membership_delete'),
    path('tasa/actualizar/', ExchangeRateUpdateView.as_view(), name='update_rate'),
    path('facturas/', InvoiceListView.as_view(), name='invoice_list'),
    path('facturas/<int:pk>/', InvoiceDetailView.as_view(), name='invoice_detail'),
    path('facturas/<int:pk>/imprimir/', PrintInvoiceActionView.as_view(), name='print_invoice'),
    path('facturas/<int:pk>/eliminar/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('reportes/', ReportView.as_view(), name='report'),
    path('reportes/enviar/', ReportSendView.as_view(), name='report_send'),
]
