# Generated by Django 4.2.11 on 2026-05-05 23:18

import apps.clients.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('codigo_afiliado', models.CharField(max_length=20, unique=True, verbose_name='Cód. Afiliado')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clients/photos/')),
                ('face_id_embeddings', apps.clients.fields.SQLiteJSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
            },
        ),
    ]
