# Generated by Django 4.2.11 on 2026-05-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='clients/enrollment/'),
        ),
        migrations.AddField(
            model_name='client',
            name='foto_perfil_der',
            field=models.ImageField(blank=True, null=True, upload_to='clients/enrollment/'),
        ),
        migrations.AddField(
            model_name='client',
            name='foto_perfil_izq',
            field=models.ImageField(blank=True, null=True, upload_to='clients/enrollment/'),
        ),
    ]
