# Generated by Django 4.2.11 on 2026-05-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_foto_frente_client_foto_perfil_der_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='foto',
        ),
    ]
