# Generated by Django 4.2.11 on 2026-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='client',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1, verbose_name='Sexo'),
        ),
    ]
