# Generated by Django 4.2.11 on 2026-05-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('resultado', models.BooleanField(default=True, verbose_name='Acceso Concedido')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo/Detalle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='clients.client', verbose_name='Afiliado')),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
